name: Deploy with Ansible

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: ansiblerole

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  


      - name: Install Ansible Role
        run: |
          ansible-galaxy install -p ./roles geerlingguy.apache
      
      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i /home/shruti/inventory  ./ansible/site.yaml
        # Optional: Add your private SSH key as a GitHub secret and use it like this:
        # env:
        #   ANSIBLE_HOST_KEY_CHECKING: False
        #   ANSIBLE_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # run: |
        #   echo "$ANSIBLE_PRIVATE_KEY" > ~/.ssh/id_rsa
        #   chmod 600 ~/.ssh/id_rsa
        #   ansible-playbook -i inventory.ini site.yml

